---
kind: pipeline
type: docker
name: ubuntu2004

workspace:
  path: /drone/Cloud_tools

steps:
  - name: Lint
    image: quay.io/ansible/toolset
    environment:
      MOLECULE_DISTRO: ubuntu2004
      # This defaults to "../.." for local manual running of molecule
      # Drone imports the role into /drone/<rolename> so we have to be explict
      # to find it when drone is running molecule.  See molecule.yml converge.yml
      ROLE_PATH: /drone/Cloud_tools
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: quay.io/ansible/toolset
    environment:
      MOLECULE_DISTRO: ubuntu2004
      ROLE_PATH: /drone/Cloud_tools
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: ubuntu1804

workspace:
  path: /drone/Cloud_tools

steps:
  - name: Lint
    image: quay.io/ansible/toolset
    environment:
      MOLECULE_DISTRO: ubuntu1804
      ROLE_PATH: /drone/Cloud_tools
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: quay.io/ansible/toolset
    environment:
      MOLECULE_DISTRO: ubuntu1804
      ROLE_PATH: /drone/Cloud_tools
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

