---
kind: pipeline
type: docker
name: ubuntu2204

workspace:
  path: /drone/Cloud_tools

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qE 'cloud_tools.yml|.drone.yml|molecule/.*.yml' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu2204
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test

---
kind: pipeline
type: docker
name: ubuntu2004

workspace:
  path: /drone/Cloud_tools

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qE 'cloud_tools.yml|.drone.yml|molecule/.*.yml' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu2004
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test

---
kind: pipeline
type: docker
name: ubuntu1804

workspace:
  path: /drone/Cloud_tools

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qE 'cloud_tools.yml|.drone.yml|molecule/.*.yml' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu1804
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test

