---
kind: pipeline
type: docker
name: ubuntu2204

# Need to define workspace as role name so molecule can find it
workspace:
  path: /drone/${DRONE_REPO_NAME}

# Have to define env variables in EACH step, not as overall pipeline
# setup :(  Due to drone-cli using old code
# https://discourse.drone.io/t/global-environment-settings-do-not-work-for-local-drone-exec/8786
#
# environment:
#   MOLECULE_DISTRO: ubuntu2004

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  # Looking for all .yml files to trigger Lint and Test
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qvE '.*.md' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu2204
      # Set this to name the molecule instance in molecule.yml
      DRONE_REPO_NAME: ${DRONE_REPO_NAME}
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test
    # volumes:
    #   - name: dockersock
    #     path: /var/run/docker.sock

# volumes:
#   - name: dockersock
#     host:
#       path: /var/run/docker.sock

image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
type: docker
name: ubuntu2004

# Need to define workspace as role name so molecule can find it
workspace:
  path: /drone/${DRONE_REPO_NAME}

# Have to define env variables in EACH step, not as overall pipeline
# setup :(  Due to drone-cli using old code
# https://discourse.drone.io/t/global-environment-settings-do-not-work-for-local-drone-exec/8786
#
# environment:
#   MOLECULE_DISTRO: ubuntu2004

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  # Looking for all .yml files to trigger Lint and Test
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qvE '.*.md' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu2004
      # Set this to name the molecule instance in molecule.yml
      DRONE_REPO_NAME: ${DRONE_REPO_NAME}
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test
    # volumes:
    #   - name: dockersock
    #     path: /var/run/docker.sock

# volumes:
#   - name: dockersock
#     host:
#       path: /var/run/docker.sock

image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
type: docker
name: ubuntu1804

# Need to define workspace as role name so molecule can find it
workspace:
  path: /drone/${DRONE_REPO_NAME}

# Have to define env variables in EACH step, not as overall pipeline
# setup :(  Due to drone-cli using old code
# https://discourse.drone.io/t/global-environment-settings-do-not-work-for-local-drone-exec/8786
#
# environment:
#   MOLECULE_DISTRO: ubuntu1804

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  # Looking for all .yml files to trigger Lint and Test
  - name: Skip
    image: docker.io/halfwalker/alpineset2
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qvE '.*.md' || exit 78

  - name: Lint
    image: docker.io/halfwalker/alpineset2
    pull: if-not-exists
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: docker.io/halfwalker/alpineset2
    environment:
      MOLECULE_DISTRO: ubuntu1804
      # Set this to name the molecule instance in molecule.yml
      DRONE_REPO_NAME: ${DRONE_REPO_NAME}
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - molecule --version
      - molecule test
    # volumes:
    #   - name: dockersock
    #     path: /var/run/docker.sock

# volumes:
#   - name: dockersock
#     host:
#       path: /var/run/docker.sock

image_pull_secrets:
  - dockerconfigjson

