---
kind: pipeline
type: docker
name: default

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: Lint
    image: quay.io/ansible/toolset
    commands:
      - yamllint .
      - ansible-lint --force-color

