---

- become: yes
  block:

#
# Install AWS cli tools
#

  - name: Remove existing config files if force_update == true
    file:
      path: "{{ item }}"
      state: absent
    when: force_update
    with_items:
      - "/home/{{ username }}/.aws/aws-config"
      - "/home/{{ username }}/.aws/aws-credentials"
    become_user: "{{ username }}"

  - name: Ensure config dirs are there
    file:
      path: "/home/{{ username }}/{{ item }}"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
    with_items:
      - .aws
    tags:
      - conffiles

  - name: Copy .aws configuration files if not there
    copy:
      src: "{{ item }}"
      dest: /home/{{ username }}/.aws/{{ item }}
      force: no
      owner: "{{ username }}"
      group: "{{ username }}"
    with_items:
      - aws-config
      - aws-credentials
    tags:
      - conffiles

  # Only run when NOT in check mode, as python pkg_resources may not yet
  # have been installed by "Install general packages" task
  - name: Install packages via pip
    pip:
      name: "{{ cloud_pip_packages }}"
      state: present
    when: ansible_check_mode == false

  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html
  - name: Install binary version of Amazon ECS cli tool
    get_url:
      url: https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      dest: /usr/local/bin/ecs-cli
      mode: u=rwx,g=rx,o=rx
    when: server_only is not defined

  # https repos won't go through apt-cacher, so bypass them
  # NOTE: This has url patterns matching https repos from below
  - name: Copy azure-specific apt config to bypass any apt-cacher-ng
    copy:
      src: 11cloud_tools.apt
      dest: /etc/apt/apt.conf.d/11cloud_tools

#
# Install Azure cli
#

  - name: Add Microsoft Azure key
    apt_key:
      url: "{{ item }}"
      state: present
    with_items:
      - https://packages.microsoft.com/keys/microsoft.asc

  - name: Install Microsoft repo
    apt_repository:
      repo: "deb https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install Microsoft Azure cli tool
    apt:
      state: present
      install_recommends: no
      name: azure-cli

#
# Install Helm
#

  - name: Add Helm key
    apt_key:
      url: "{{ item }}"
      state: present
    with_items:
      - https://baltocdn.com/helm/signing.asc

  - name: Install Helm repo
    apt_repository:
      repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
      state: present
      update_cache: yes

  - name: Install Helm cli tool
    apt:
      state: present
      install_recommends: no
      name: helm

#
# Install Kubernetes tools
#

  - name: Add Google Kubernetes key
    apt_key:
      url: "{{ item }}"
      state: present
    with_items:
      - https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: Install Kubernetes repo - ugh for bionic have to use xenial
    apt_repository:
      repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      state: present
      update_cache: yes

  - name: Install Kubernetes kubectl cli tool
    apt:
      state: present
      install_recommends: no
      name: kubectl

#
# Install Skaffold directly
#

  - name: Add Skaffold binary
    get_url:
      url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      dest: /usr/local/bin/skaffold
      mode: 0755

#
# Install minikube directly
# https://minikube.sigs.k8s.io/docs/start/
#

  - name: Add minikube binary
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /usr/local/bin/minikube
      mode: 0755

  #
  # block

