---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: "${DRONE_REPO_NAME:-instance}-${MOLECULE_DISTRO:-ubuntu2204}"
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    network: podman_2204
    env:
      USER: podman

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  # For podman - https://www.ansible.com/blog/developing-and-testing-ansible-roles-with-molecule-and-podman-part-1
  #   ssh_connection:
  #     pipelining: false
  inventory:
    group_vars:
      all:
        vault_github_auth:
          name: $GH_USER
          token: $GH_TOKEN
        # Create a testing user in molecule/default/prepare.yml
        username: testing
        groupname: testing
  env:
    USER: podman
    GH_USER: ${GH_USER:-""}
    GH_TOKEN: ${GH_TOKEN:-""}

verifier:
  name: testinfra
  # name: goss
  # env:
  #   GH_USER: ${GH_USER:-""}
  #   GH_TOKEN: ${GH_TOKEN:-""}

scenario:
  name: default
  test_sequence:
    # - lint    # causes molecule test to error out - meh we lint in drone anyway
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy
