---

dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: "instance-${MOLECULE_DISTRO:-ubuntu2004}"
    # Default to dockerhub unless a local cache is defined
    # Default to ubuntu2004 unless a distro is defined
    image: "${HUB_CACHE:-registry.hub.docker.com}/geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    # https://github.com/ansible-community/molecule/issues/1331
    # registry:
    #   url: https://registry.hub.docker.com/
    #   credentials:
    #     username: ${DOCKER_USER}
    #     password: ${DOCKER_PASS}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  options:
    # Some tasks we don't need/want to run again for idempotence testing
    # https://univers-libre.net/posts/ansible-molecule.html
    skip-tags: molecule-idempotence-notest
  env:
    GH_USER: ${GH_USER-""}
    GH_TOKEN: ${GH_TOKEN-""}

verifier:
  name: goss

