---

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:

    - name: Install ZSH
      apt:
        state: present
        update_cache: yes
        name:
          - zsh

    - name: Create blank /root/.zshrc
      file:
        path: "/root/.zshrc"
        owner: root
        group: root
        mode: 0644
        state: touch
