---

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:

    - name: Add testing user
      user:
        name: testing
        comment: Test user for cloud_tools

    # python3-debian Required for deb822_repository tasks
    - name: Install support packages
      apt:
        state: present
        install_recommends: no
        update_cache: yes
        name: 
          - python3-debian
          - zsh

    - name: Create blank /root/.zshrc
      file:
        path: "/root/.zshrc"
        owner: root
        group: root
        mode: 0644
        state: touch
